services:
  web:
    build: .
    container_name: crud-using-domain-oriented-container
    volumes:
      - .:/var/www
    restart: unless-stopped
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_DATABASE=simple_crud_db"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db
    networks:
      - simple-crud-network
  db:
     image: postgres:latest
     container_name: crud-using-domain-oriented-db-container
     restart: unless-stopped
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: simple-crud-db
     ports:
       - "5432:5432"
     volumes:
       - simple-crud-pgsql:/var/lib/postgresql/data
     networks:
       - simple-crud-network
  nginx:
    image: nginx:alpine
    container_name: crud-using-domain-oriented-nginx-container
    restart: unless-stopped
    ports:
      - "8900:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
        - simple-crud-network

volumes:
   simple-crud-pgsql:
networks:
  simple-crud-network:
    driver: bridge


